language: python
cache: pip
python:
  - '3.4'
  - '3.5'
  - '3.6'
  - 'nightly'
install:
  - pip install -U Cython pytest pytest-cov 'pytest-asyncio<0.6'
  - pip install -Ue .
script:
  - py.test --cov=aiofile tests
  - pip uninstall -y .
